# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # carbon is the codename for latest lts version (e.g. 8.9.1):
      - image: circleci/node:carbon
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: npm install

      - run:
          name: Test runner
          command: npm test

      - run:
          name: Test coverage
          command: cat ./coverage/lcov.info

      - save_cache:
          name: Save node_modules cache
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
